### ISSUE TITLE
Issue: vegafusion

### ISSUE THREAD

**Issue by chrisgqy** [UBC-MDS/2023-DSCI522-Group22#7]
I heard that many of our classmates  were encountering issues when creating Docker files with the package vegafusion. We might run into this obstacle too. Anyone knows what is the current fix?

**Comment by lichunubc** [comment]
If I recall correctly, we only use Vega Fusion if the data exceeds 5000 lines. I'm open to suggestions, but one potential solution is to adjust the train/test split to 70%/30% instead of 80%/20%. This adjustment would reduce the size of the training set to slightly under 5000 observations without compromising the integrity of our model.

**Comment by jcairn02** [comment]
I like the 70/30 solution! It's possible that is the correct ratio to begin with. 
The change is minimal and it avoids the problem

**Comment by jinyz8888** [comment]
Yes, we can split it to 70%|30%.

**Comment by chrisgqy** [comment]
Yeah I think 70-30 solution sounds great! This can avoid some problem with installing vegafusion.
